private ["_Weapon"];
(findDisplay 106) closeDisplay 0;
_Weapon = secondaryWeapon player;
player selectWeapon _Weapon;
reload player;
sleep 1.5;
player switchMove 'ActsPercMstpSnonWpstDnon_suicide1B';
cutText ["Неужели это конец?", "PLAIN DOWN"];
sleep 3.9;
player fire (currentWeapon player);
sleep 1;
player SetDamage 2;