// Generated by unRap v1.06 by GROM

class CfgLootSmall {
//мусор
	trash[] = {
	{"TrashTinCan", 0.2},
	{"TrashJackDaniels", 0.15},
	{"ItemSodaEmpty", 0.2},
	{"ItemTrashToiletpaper", 0.13},
	{"ItemTrashRazor", 0.11}
	};
	

//Еда-вода-мусор-всякая ересь
	civilian[] = {
	{"FoodCanUnlabeled", 0.1},
	{"TrashJackDaniels", 0.09},
	{"ItemSodaEmpty", 0.05},
	{"ItemSodaCoke", 0.1},
	{"ItemSodaPepsi", 0.03},
	{"FoodCanBakedBeans", 0.02},
	{"FoodCanSardines", 0.02},
	{"FoodCanFrankBeans", 0.02},
	{"FoodCanPasta", 0.02},
	{"8Rnd_9x18_Makarov", 0.07},
	{"7Rnd_45ACP_1911", 0.05},
	{"2Rnd_shotgun_74Slug", 0.08},
	{"2Rnd_shotgun_74Pellets", 0.08},
	{"ItemBandage", 0.06},
	{"ItemPainkiller", 0.06},
	{"FoodBioMeat", 0.01},
	{"8Rnd_9x18_MakarovSD", 0.01}
	};

	office2[] = {
	{"FoodCanUnlabeled", 0.05},
	{"TrashJackDaniels", 0.09},
	{"ItemSodaEmpty", 0.1},
	{"ItemSodaCoke", 0.02},
	{"ItemSodaPepsi", 0.02},
	{"FoodCanBakedBeans", 0.03},
	{"FoodCanSardines", 0.03},
	{"FoodCanFrankBeans", 0.03},
	{"FoodCanPasta", 0.03},
	{"8Rnd_9x18_Makarov", 0.07},
	{"7Rnd_45ACP_1911", 0.05},
	{"2Rnd_shotgun_74Slug", 0.08},
	{"2Rnd_shotgun_74Pellets", 0.08},
	{"ItemBandage", 0.05},
	{"ItemPainkiller", 0.06},
	{"FoodBioMeat", 0.01},
	{"8Rnd_9x18_MakarovSD", 0.01}
	};

	food[] = {
	{"TrashTinCan", 0.1},
	{"TrashJackDaniels", 0.1},
	{"ItemSodaEmpty", 0.1},
	{"ItemSodaCoke", 0.02},
	{"ItemSodaPepsi", 0.03},
	{"FoodCanBakedBeans", 0.04},
	{"FoodCanSardines", 0.04},
	{"FoodCanFrankBeans", 0.04},
	{"FoodCanPasta", 0.04},
	{"FoodCanUnlabeled", 0.05},
	{"FoodPistachio", 0.03},
	{"FoodNutmix", 0.02}
	};

	office[] = {
	{"FoodCanUnlabeled", 0.08},
	{"ItemSodaEmpty", 0.1},
	{"ItemSodaCoke", 0.03},
	{"ItemSodaPepsi", 0.02},
	{"TrashJackDaniels", 0.1},
	{"FoodCanBakedBeans", 0.01},
	{"FoodCanSardines", 0.01},
	{"FoodCanFrankBeans", 0.01},
	{"FoodCanPasta", 0.01},
	{"ItemWaterbottleUnfilled", 0.01},
	{"ItemWaterbottle", 0.01},
	{"ItemBandage", 0.08},
	{"7Rnd_45ACP_1911", 0.04},
	{"5x_22_LR_17_HMR", 0.01},
	{"10x_303", 0.04},
	{"6Rnd_45ACP", 0.04},
	{"2Rnd_shotgun_74Slug", 0.07},
	{"2Rnd_shotgun_74Pellets", 0.07},
	{"8Rnd_9x18_Makarov", 0.09},
	{"15Rnd_W1866_Slug", 0.02},
	{"WoodenArrow", 0.06},
	{"HandRoadFlare", 0.07},
	{"ItemPainkiller", 0.02},
	{"HandChemGreen", 0.06},
	{"HandChemBlue", 0.06},
	{"HandChemRed", 0.06},
	{"ItemHeatPack", 0.03}
	};

	generic[] = {
	{"FoodCanUnlabeled", 0.07},
	{"ItemSodaEmpty", 0.1},
	{"ItemSodaCoke", 0.03},
	{"ItemSodaPepsi", 0.02},
	{"TrashJackDaniels", 0.1},
	{"FoodCanBakedBeans", 0.01},
	{"FoodCanSardines", 0.01},
	{"FoodCanFrankBeans", 0.01},
	{"FoodCanPasta", 0.01},
	{"ItemWaterbottleUnfilled", 0.01},
	{"ItemWaterbottle", 0.01},
	{"ItemBandage", 0.11},
	{"7Rnd_45ACP_1911", 0.03},
	{"5x_22_LR_17_HMR", 0.01},
	{"10x_303", 0.04},
	{"6Rnd_45ACP", 0.04},
	{"2Rnd_shotgun_74Slug", 0.08},
	{"2Rnd_shotgun_74Pellets", 0.08},
	{"8Rnd_9x18_Makarov", 0.09},
	{"15Rnd_W1866_Slug", 0.02},
	{"WoodenArrow", 0.06},
	{"HandRoadFlare", 0.07},
	{"ItemPainkiller", 0.02},
	{"HandChemGreen", 0.07},
	{"HandChemBlue", 0.07},
	{"HandChemRed", 0.07},
	{"ItemHeatPack", 0.04}
	};

//Медицина
	medical[] = {
	{"ItemBandage", 0.3},
	{"ItemPainkiller", 0.15},
	{"ItemMorphine", 0.2},
	{"ItemEpinephrine", 0.1},
	{"ItemAntibiotic", 0.05},
	{"ItemHeatPack", 0.05}
	};

	hospital[] = {
	{"ItemBandage", 0.33},
	{"ItemPainkiller", 0.16},
	{"ItemMorphine", 0.13},
	{"ItemEpinephrine", 0.1},
	{"ItemBloodbag", 0.05},
	{"ItemAntibiotic", 0.03}
	};

//Военные здания
	military[] = {
	{"FoodCanUnlabeled", 0.08},
	{"ItemSodaEmpty", 0.1},
	{"ItemSodaCoke", 0.01},
	{"ItemSodaPepsi", 0.01},
	{"ItemBandage", 0.04},
	{"ItemAntibiotic", 0.01},
	{"ItemPainkiller", 0.04},
	{"ItemMorphine", 0.01},
	{"30Rnd_556x45_Stanag", 0.04},
	{"20Rnd_762x51_DMR", 0.02},
	{"17Rnd_9x19_glock17", 0.05},
	{"15Rnd_9x19_M9SD", 0.01},
	{"15Rnd_9x19_M9", 0.02},
	{"30Rnd_762x39_AK47", 0.04},
	{"30Rnd_545x39_AK", 0.03},
	{"5Rnd_762x51_M24", 0.01},
	{"5Rnd_86x70_L115A1", 0.01},
	{"8Rnd_B_Beneli_74Slug", 0.07},
	{"1Rnd_HE_M203", 0.01},
	{"FlareWhite_M203", 0.06},
	{"FlareGreen_M203", 0.06},
	{"1Rnd_Smoke_M203", 0.06}, 
	{"200Rnd_556x45_M249", 0.01},
	{"HandGrenade_west", 0.01},
	{"HandGrenade_east", 0.01},
	{"SmokeShell", 0.06},
	{"SmokeShellRed", 0.06},
	{"SmokeShellGreen", 0.06},
	{"8Rnd_B_Beneli_Pellets", 0.08},
	{"30Rnd_556x45_StanagSD", 0.01},
	{"30Rnd_9x19_MP5", 0.04},
	{"30Rnd_9x19_MP5SD", 0.01},
	{"100Rnd_762x51_M240", 0.01},
	{"HandChemGreen", 0.07},
	{"HandChemBlue", 0.07},
	{"HandChemRed", 0.07},
	{"ItemHeatPack", 0.04},
	{"8Rnd_9x18_MakarovSD", 0.01},
	{"20Rnd_B_765x17_Ball", 0.04},
	{"30Rnd_9x19_UZI_SD", 0.01}
	};

//Зомби полицейский
	policeman[] = {
	{"ItemBandage", 0.3},
	{"7Rnd_45ACP_1911", 0.08},
	{"6Rnd_45ACP", 0.1},
	{"15Rnd_W1866_Slug", 0.08},
	{"8Rnd_B_Beneli_Pellets", 0.17},
	{"HandRoadFlare", 0.1},
	{"8Rnd_9x18_MakarovSD", 0.01},
	{"ItemComboLock", 0.02},
	{"SmokeShell", 0.08},
	{"ItemHotwireKit", 0.01}
	};

//Охотничьи вышки
	hunter[] = {
	{"FoodMRE", 0.01}
	};

//Сараи-амбары-коровники
	worker[] = {
	{"FoodCanUnlabeled", 0.06},
	{"TrashJackDaniels", 0.1},
	{"ItemSodaEmpty", 0.1},
	{"ItemSodaCoke", 0.04},
	{"ItemSodaPepsi", 0.04},
	{"FoodCanBakedBeans", 0.03},
	{"FoodCanSardines", 0.03},
	{"FoodCanFrankBeans", 0.03},
	{"FoodCanPasta", 0.03},
	{"ItemBandage", 0.1},
	{"ItemPainkiller", 0.06},
	{"ItemComboLock", 0.01},
	{"ItemSledgeHead", 0.02}
	};

//Скины
	clothes[] = {
	{"Skin_RU_Policeman_DZ", 0.13},
	{"Skin_Pilot_EP1_DZ", 0.12},
	{"Skin_Functionary1_EP1_DZ", 0.1},
	{"Skin_Priest_DZ", 0.1},
	{"Skin_Rocker1_DZ", 0.07},
	{"Skin_Rocker2_DZ", 0.07},
	{"Skin_Rocker3_DZ", 0.08},
	{"Skin_Rocker4_DZ", 0.08},
	{"Skin_SurvivorW3_DZ", 0.09},
	{"Skin_SurvivorWpink_DZ", 0.09},
	{"Skin_SurvivorWurban_DZ", 0.07}
	};

//Военные скины
	militaryclothes[] = {
	{"Skin_Camo1_DZ", 0.1},
	{"Skin_Sniper1_DZ", 0.08},
	{"Skin_Rocket_DZ", 0.05},
	{"Skin_Soldier1_DZ", 0.13},
	{"Skin_Drake_Light_DZ", 0.07},
	{"Skin_Soldier_TL_PMC_DZ", 0.07},
	{"Skin_Soldier_Sniper_PMC_DZ", 0.05},
	{"Skin_Soldier_Bodyguard_AA12_PMC_DZ", 0.07},
	{"Skin_CZ_Special_Forces_GL_DES_EP1_DZ", 0.08},
	{"Skin_FR_OHara_DZ", 0.08},
	{"Skin_FR_Rodriguez_DZ", 0.09},
	{"Skin_CZ_Soldier_Sniper_EP1_DZ", 0.04},
	{"Skin_Graves_Light_DZ", 0.09}
	};

//Специализированные скины
	specialclothes[] = {
	{"Skin_Ins_Soldier_GL_DZ", 0.1},
	{"Skin_GUE_Commander_DZ", 0.08},
	{"Skin_Bandit1_DZ", 0.13},
	{"Skin_Bandit2_DZ", 0.06},
	{"Skin_BanditW1_DZ", 0.07},
	{"Skin_BanditW2_DZ", 0.07},
	{"Skin_TK_INS_Soldier_EP1_DZ", 0.05},
	{"Skin_TK_INS_Warlord_EP1_DZ", 0.07},
	{"Skin_SurvivorWcombat_DZ", 0.08},
	{"Skin_SurvivorWdesert_DZ", 0.08},
	{"Skin_GUE_Soldier_MG_DZ", 0.05},
	{"Skin_GUE_Soldier_Sniper_DZ", 0.04},
	{"Skin_GUE_Soldier_Crew_DZ", 0.04},
	{"Skin_GUE_Soldier_CO_DZ", 0.04},
	{"Skin_GUE_Soldier_2_DZ", 0.04}
	};

//Патроны к военной технике
	machinegunammoexpl[] = {
	{"100Rnd_556x45_BetaCMag", 0.17},
	{"75Rnd_545x39_RPK", 0.15},
	{"100Rnd_556x45_M249", 0.07},
	{"100Rnd_762x51_M240", 0.07},
	{"100Rnd_762x54_PK", 0.06},
	{"200Rnd_556x45_M249", 0.12},
	{"PipeBomb", 0.01}
	};

//Пистолеты
	pistols[] = {
	{"Makarov", 0.3},
	{"Colt1911", 0.18},
	{"revolver_EP1", 0.2},
	{"glock17_EP1", 0.1},
	{"MakarovSD", 0.07},
	{"M9", 0.07},
	{M9SD, 0.02},
	{"revolver_gold_EP1", 0.01}
	};
};
